# Preparation

Preparation biasa dilakukan untuk mempersiapkan data sebelum masuk dalam tahap pemodelan. <br>
Berikut adalah tahapan yang akan dilalui pada data `SC_HW1_bank_data.csv` sebelum tahap pemodelan :
1. Import Library
2. Input Dataset
3. Preprocessing
4. Train-Test Split

## Import Library

In [ ]:
import pandas as pd
import numpy as np

## Input Dataset

In [ ]:
#Membaca data dan memasukkannya ke dalam bentuk Pandas Dataframe
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')

In [ ]:
#Jalankan code untuk mengecek nama kolom yang tersedia
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df

,RowNumber,CustomerId,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
#Hilangkan kolom yang dirasa tidak relevan dengan model (contoh: ID). None dapat diisi dengan nama-nama kolom yang akan digunakan.
#Contoh df = df[['X1','X2', 'Y']].copy()

#START CODE
df = df[['Geography', 	'Gender', 	'Age', 	'Tenure', 	'Balance', 	'NumOfProducts', 	'HasCrCard', 	'IsActiveMember', 	'EstimatedSalary', 	'Exited']].copy()

In [ ]:
df

,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,France,Female,42,2,0.00,1,1,1,101348.88,1
1,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,France,Female,39,1,0.00,2,0,0,93826.63,0
4,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...
9995,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Preprocessing

In [ ]:
#Lakukan One-Hot Encoder untuk data categorical, dengan fungsi pandas get_dummies

#START CODE
df = pd.get_dummies(df)

In [ ]:
#Pisahkan mana X (feature) dengan Y,
#Y adalah kolom "Exited"

#START CODE
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [ ]:
#Lakukan Scaler dan/atau Noermalisasi jika diperlukan
from sklearn.preprocessing import MinMaxScaler

#START CODE
scaler = MinMaxScaler()
X_transform = scaler.fit_transform(X)

In [ ]:
#Ini digunakan jika dilakukan scaler/Normalisas. Jika tidak, code ini bisa dilewat dan diganti dengan code yang ada di dalam komen
X_transform = pd.DataFrame(X_transform, columns = X.columns)
#X_transform = X.copy()

## Train-Test Split

In [ ]:
#Split menjadi train dan test dengan test_size 25%
#Tidak perlu mengubah code ini

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_transform,y,test_size = 0.25,random_state = 123)

# Modeling

## Model1

Model 1 Random Forest

### Soal :
Jelaskan secara Singkat Model pertama yang digunakan!

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params1 = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}

from sklearn.ensemble import RandomForestClassifier
#START CODE
model1 = RandomForestClassifier()
params1 = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, None],
    'max_features': ['sqrt', 'log2'],
    'min_samples_split': [2, 4, 6]
}
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan

from sklearn.model_selection import GridSearchCV
grid_RF = GridSearchCV(
             estimator=model1,
             param_grid=params1,
             cv=5,
             n_jobs=-1)

grid_RF.fit(X_train,y_train)
grid_RF.best_params_

{'max_depth': None,
 'max_features': 'log2',
 'min_samples_split': 4,
 'n_estimators': 200}

In [ ]:
#lakukan evaluasi dengan beberapa maetric di bawah ini
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid_RF.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1983
           1       0.78      0.47      0.59       517

    accuracy                           0.86      2500
   macro avg       0.83      0.72      0.75      2500
weighted avg       0.86      0.86      0.85      2500


[[1913   70]
 [ 272  245]]

0.8632

## Model2
### Soal :
Jelaskan secara Singkat Model ke-2 yang digunakan!

Model 2 Decision Tree

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}

from sklearn.tree import DecisionTreeClassifier

#START CODE
model2 = DecisionTreeClassifier()
params2 = {
    'max_depth': [3, 5, 7, 9],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [None, 'sqrt', 'log2']
}
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV
grid_DecisionTree = GridSearchCV(
             estimator= model2,
             param_grid= params2,
             scoring = 'accuracy',
             n_jobs = 10, # core cpu yang digunakan
             cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid_DecisionTree.fit(X_train,y_train)
grid_DecisionTree.best_params_

{'max_depth': 7,
 'max_features': None,
 'min_samples_leaf': 4,
 'min_samples_split': 2}

In [ ]:
#lakukan evaluasi
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid_DecisionTree.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.96      0.92      1983
           1       0.77      0.46      0.58       517

    accuracy                           0.86      2500
   macro avg       0.82      0.71      0.75      2500
weighted avg       0.85      0.86      0.85      2500


[[1912   71]
 [ 278  239]]

0.8604

## Model3
### Soal :
Jelaskan secara Singkat Model ke-3 yang digunakan!

Model 3 Naive Bayes

In [ ]:

#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}

from sklearn.naive_bayes import BernoulliNB


#START CODE
model3 = BernoulliNB()
params = {
    'alpha': [0.1, 0.5, 1.0],
    'fit_prior': [True, False]
}
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(
             estimator= model3,
             param_grid= params,
             scoring = 'accuracy',
             n_jobs = 5, # core cpu yang digunakan
             cv = 5 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid.fit(X_train,y_train)
grid.best_params_

{'alpha': 0.1, 'fit_prior': True}

In [ ]:
#lakukan evaluasi
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1983
           1       0.45      0.29      0.35       517

    accuracy                           0.78      2500
   macro avg       0.64      0.60      0.61      2500
weighted avg       0.75      0.78      0.76      2500


[[1801  182]
 [ 368  149]]

0.78

## Tarik Kesimpulan Model Mana yang terbaik beserta alasannya

In [ ]:
from sqlalchemy.sql.schema import ForeignKeyConstraint
Berdasarkan hasil performa tiga model machine learning terbaik adalah Random Forest dan Decision Tree memiliki performa yang hampir
 sama dengan akurasi sekitar 0.86. Sedangkan model Naive Bayes-Bernoulli memiliki akurasi yang lebih rendah dibandingkan kedua model lainnya.
  1. Random Forest : 0.8632
  2. Decision Tree : 0.8604
  3. Naive Bayes-Bernoulli : 0.78